<a href="https://colab.research.google.com/github/V-arshaSharma/Data-Expolatory-/blob/main/Mckinsey_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
!gdown 1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_

Downloading...
From: https://drive.google.com/uc?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
To: /content/mckinsey.csv
100% 83.8k/83.8k [00:00<00:00, 80.4MB/s]

In [4]:
df = pd.read_csv("mckinsey.csv")

In [5]:
df.shape

(1704, 6)

In [6]:
df.shape[1]

6

In [7]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [8]:
# first five row of data
df.iloc[0:5]

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [9]:
df.loc[0:4]

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [10]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [11]:
df.tail() #last 5 rows

       country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [12]:
 df.iloc[-3:] #last 3 rows

       country  year  population continent  life_exp     gdp_cap
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [13]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [14]:
# display all the record of iceland
df.query('country == "Iceland"')

     country  year  population continent  life_exp       gdp_cap
684  Iceland  1952      147962    Europe    72.490   7267.688428
685  Iceland  1957      165110    Europe    73.470   9244.001412
686  Iceland  1962      182053    Europe    73.680  10350.159060
687  Iceland  1967      198676    Europe    73.730  13319.895680
688  Iceland  1972      209275    Europe    74.460  15798.063620
689  Iceland  1977      221823    Europe    76.110  19654.962470
690  Iceland  1982      233997    Europe    76.990  23269.607500
691  Iceland  1987      244676    Europe    77.230  26923.206280
692  Iceland  1992      259012    Europe    78.770  25144.392010
693  Iceland  1997      271192    Europe    78.950  28061.099660
694  Iceland  2002      288030    Europe    80.500  31163.201960
695  Iceland  2007      301931    Europe    81.757  36180.789190

In [16]:
# using masking get iceland records
mask = df['country'] == 'Iceland'
df[mask] #extract all records

     country  year  population continent  life_exp       gdp_cap
684  Iceland  1952      147962    Europe    72.490   7267.688428
685  Iceland  1957      165110    Europe    73.470   9244.001412
686  Iceland  1962      182053    Europe    73.680  10350.159060
687  Iceland  1967      198676    Europe    73.730  13319.895680
688  Iceland  1972      209275    Europe    74.460  15798.063620
689  Iceland  1977      221823    Europe    76.110  19654.962470
690  Iceland  1982      233997    Europe    76.990  23269.607500
691  Iceland  1987      244676    Europe    77.230  26923.206280
692  Iceland  1992      259012    Europe    78.770  25144.392010
693  Iceland  1997      271192    Europe    78.950  28061.099660
694  Iceland  2002      288030    Europe    80.500  31163.201960
695  Iceland  2007      301931    Europe    81.757  36180.789190

In [23]:
# from df, find the average TOTAL gdp of iceland the year 2007

df3 = df.query('country == "Iceland" and year < 2000')
df3["total_gdp"] = df3['population'] * df3['gdp_cap']

<ipython-input-23-cb159bd07c16>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["total_gdp"] = df3['population'] * df3['gdp_cap']

In [25]:
df3 = df.query('country == "Iceland" and year < 2000') .copy() #here we make a copy to avoid above warning error
df3["total_gdp"] = df3['population'] * df3['gdp_cap']

In [26]:
df3

,country,year,population,continent,life_exp,gdp_cap,tota_gdp,total_gdp
684,Iceland,1952,147962,Europe,72.49,7267.688428,1.075342e+09,1.075342e+09
685,Iceland,1957,165110,Europe,73.47,9244.001412,1.526277e+09,1.526277e+09
686,Iceland,1962,182053,Europe,73.68,10350.159060,1.884278e+09,1.884278e+09
687,Iceland,1967,198676,Europe,73.73,13319.895680,2.646344e+09,2.646344e+09
688,Iceland,1972,209275,Europe,74.46,15798.063620,3.306140e+09,3.306140e+09
689,Iceland,1977,221823,Europe,76.11,19654.962470,4.359923e+09,4.359923e+09
690,Iceland,1982,233997,Europe,76.99,23269.607500,5.445018e+09,5.445018e+09
691,Iceland,1987,244676,Europe,77.23,26923.206280,6.587462e+09,6.587462e+09
692,Iceland,1992,259012,Europe,78.77,25144.392010,6.512699e+09,6.512699e+09
693,Iceland,1997,271192,Europe,78.95,28061.099660,7.609946e+09,7.609946e+09

In [27]:
df3['total_gdp'].mean() #average

4095342816.207885

In [28]:
int(df3['total_gdp'].mean())

4095342816

In [31]:
df3['total_gdp'].aggregate(['sum', 'max', 'min', 'mean', 'count', 'median'])

sum       4.095343e+10
max       7.609946e+09
min       1.075342e+09
mean      4.095343e+09
count     1.000000e+01
median    3.833031e+09
Name: total_gdp, dtype: float64

In [32]:
df3['total_gdp'].aggregate(['sum', 'max', 'min', 'mean', 'count', 'median']). astype(dtype = 'int')

sum       40953428162
max        7609945738
min        1075341715
mean       4095342816
count              10
median     3833031252
Name: total_gdp, dtype: int64